=== YinaryHdz/WSActividadesLMSGI/Actividad13/_06_EmpresaDTD.dtd
<!ELEMENT empresa (nombre,nif,esEspañola, capitalSocial,direccion, empleados)>

    <!ELEMENT nombre (#PCDATA)>

    <!ELEMENT nif (#PCDATA)>

    <!ELEMENT esEspañola (#PCDATA)>

    <!ELEMENT capitalSocial (euros|dolares|yenes)>
        <!ELEMENT euros (#PCDATA)>
        <!ELEMENT dolares (#PCDATA)>
        <!ELEMENT yenes (#PCDATA)>

    <!ELEMENT direccion (tipo_via,nombre_via,codigo_postal,pais)>
        <!ELEMENT tipo_via (#PCDATA)>
        <!ELEMENT nombre_via (#PCDATA)>
        <!ELEMENT codigo_postal (#PCDATA)>
        <!ELEMENT pais (#PCDATA)>

    <!ELEMENT empleados (empleado+)>
        <!ELEMENT empleado (nombre, apellidos+, DNI, esExtranjero, fechaNacimiento, salario, direccionEmpleado+, estaCasado?)>
        <!ELEMENT apellidos (#PCDATA)>
        <!ELEMENT DNI (#PCDATA)>
        <!ELEMENT esExtranjero (#PCDATA)>
        <!ELEMENT fechaNacimiento (#PCDATA)>
        <!ELEMENT salario (#PCDATA)>
        <!ELEMENT direccionEmpleado (via,pais)>
            <!ELEMENT via (#PCDATA)>
        <!ELEMENT estaCasado (#PCDATA)>

=== YinaryHdz/WSActividadesLMSGI/Actividad13/_05_EmpresaDTD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE empresa SYSTEM "_06_EmpresaDTD.dtd">
<empresa>
    <nombre>Microsoft</nombre>
    <nif>Y9876459H</nif>
    <esEspañola>True</esEspañola>
    <capitalSocial>
        <euros>1000000</euros>
    </capitalSocial>
    <direccion>
        <tipo_via>Calle</tipo_via>
        <nombre_via>St Ginebra</nombre_via>
        <codigo_postal>93456</codigo_postal>
        <pais>USA</pais>
    </direccion>
    <empleados>
        <empleado>
            <nombre>John</nombre>
            <apellidos>Doe</apellidos> 
            <DNI>12345678A</DNI>
            <esExtranjero>No</esExtranjero>
            <fechaNacimiento>1990-01-01</fechaNacimiento>
            <salario>50000</salario>
            <direccionEmpleado>
                <via>Main Street</via>
                <pais>USA</pais>
            </direccionEmpleado>
            <estaCasado>False</estaCasado>
        </empleado>
        <empleado>
            <nombre>Jane</nombre>
            <apellidos>Smith</apellidos> 
            <DNI>98765432B</DNI>
            <esExtranjero>No</esExtranjero>
            <fechaNacimiento>1985-05-15</fechaNacimiento>
            <salario>60000</salario>
            <direccionEmpleado>
                <via>First Avenue</via>
                <pais>USA</pais>
            </direccionEmpleado>
            <estaCasado>False</estaCasado>
        </empleado>
    </empleados>
</empresa>
