=== YinaryHdz/WSActividadesLMSGI/Actividad13/_08_EmpresaXSD.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="empresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="nif" type="xs:string"/>
                <xs:element name="esEspaÃ±ola" type="xs:boolean"/>
                <xs:element name="capitalSocial" >
                    <xs:complexType>
                        <xs:choice>
                            <xs:element name="euros" type="xs:double"/>
                            <xs:element name="dolares" type="xs:double"/>
                            <xs:element name="yenes" type="xs:double"/>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>    
                <xs:element name="direccion">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tipo_via" type="xs:string"/>
                            <xs:element name="nombre_via" type="xs:string"/>
                            <xs:element name="codigo_postal" type="xs:string"/>
                            <xs:element name="pais" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType> 
                </xs:element>          
                <xs:element name="empleados">                     
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="empleado" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="apellidos" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                                        <xs:element name="DNI" type="xs:string"/>
                                        <xs:element name="esExtranjero" type="xs:boolean"/>
                                        <xs:element name="fechaNacimiento" type="xs:date"/>
                                        <xs:element name="salario" type="xs:integer"/>
                                        <xs:element name="direccionEmpleado" minOccurs="1" maxOccurs="2">
                                            <xs:complexType>
                                                <xs:all>
                                                    <xs:element name="via" type="xs:string"/>
                                                    <xs:element name="pais" type="xs:string"/>
                                                </xs:all>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="estaCasado" type="xs:boolean" minOccurs="0"/>    
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== YinaryHdz/WSActividadesLMSGI/Actividad13/_07_EmpresaXSD.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="_08_EmpresaXSD.xsd">
    <nombre>Microsoft</nombre>
    <nif>Y9876459H</nif>
    <esEspañola>true</esEspañola>
    <capitalSocial>
        <euros>1000000</euros>
    </capitalSocial>
    <direccion>
        <tipo_via>Calle</tipo_via>
        <nombre_via>St Ginebra</nombre_via>
        <codigo_postal>93456</codigo_postal>
        <pais>USA</pais>
    </direccion>
    <empleados>
        <empleado>
            <nombre>John</nombre>
            <apellidos>Doe</apellidos> 
            <DNI>12345678A</DNI>
            <esExtranjero>false</esExtranjero>
            <fechaNacimiento>1990-01-01</fechaNacimiento>
            <salario>50000</salario>
            <direccionEmpleado>
                <via>Main Street</via>
                <pais>USA</pais>
            </direccionEmpleado>
            <estaCasado>false</estaCasado>
        </empleado>
        <empleado>
            <nombre>Jane</nombre>
            <apellidos>Smith</apellidos> 
            <DNI>98765432B</DNI>
            <esExtranjero>false</esExtranjero>
            <fechaNacimiento>1985-05-15</fechaNacimiento>
            <salario>60000</salario>
            <direccionEmpleado>
                <via>First Avenue</via>
                <pais>USA</pais>
            </direccionEmpleado>
            <estaCasado>false</estaCasado>
        </empleado>
    </empleados>
</empresa>
