<?xml version="1.0" encoding="UTF-8" standalone ="yes"?>
<!DOCTYPE videojuego [
    <!ELEMENT videojuego (info_basica,programadores,compania)>

    <!ELEMENT info_basica (titulo,fecha_creacion,nota_personal)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT fecha_creacion (#PCDATA)>
    <!ELEMENT nota_personal (#PCDATA)>

    <!ELEMENT programadores (programador+)>

    <!ELEMENT programador (nombre,apellidos,dni,fecha_nacimiento,direccion)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT dni (#PCDATA)>
    <!ELEMENT fecha_nacimiento (#PCDATA)>
    <!ELEMENT direccion (tipo_via,nombre_via,codigo_postal,pais)>
        <!ELEMENT tipo_via (#PCDATA)>
        <!ELEMENT nombre_via (#PCDATA)>
        <!ELEMENT codigo_postal (#PCDATA)>
        <!ELEMENT pais (#PCDATA)>
    
    <!ELEMENT compania (nombre,nif, direccion)>
    <!ELEMENT nif (#PCDATA)>

    <!ATTLIST videojuego id ID #REQUIRED>
    <!ATTLIST programador id CDATA #REQUIRED>
    <!ATTLIST compania identificacion CDATA #REQUIRED>
]>

<videojuego id="DEL45" >
<info_basica>
    <titulo>Mario Kart </titulo>
    <fecha_creacion>27/08/1992</fecha_creacion>
    <nota_personal> 10/10 </nota_personal> 
</info_basica>
<programadores>
    <programador id = "1">
        <nombre>Tommy</nombre>
        <apellidos>Stuart Little </apellidos>
        <dni>12345678D</dni>
        <fecha_nacimiento> 12/01/1965</fecha_nacimiento>
        <direccion>
            <tipo_via>Calle</tipo_via>
            <nombre_via>St Ginebra</nombre_via>
            <codigo_postal>93456</codigo_postal>
            <pais>USA</pais>
        </direccion>
    </programador> 
    <programador id = "2">
        <nombre>Scaarlett</nombre>
        <apellidos>Johansson </apellidos>
        <dni>98765432D</dni>
        <fecha_nacimiento>21/11/1975</fecha_nacimiento>
        <direccion>
            <tipo_via>Calle</tipo_via>
            <nombre_via>St Widow</nombre_via>
            <codigo_postal>45678</codigo_postal>
            <pais>USA</pais>
        </direccion>
    </programador> 
</programadores>
<compania identificacion="R6785">
    <nombre>Nintendo</nombre>
    <nif>98761234F</nif>
    <direccion>
        <tipo_via>Calle</tipo_via>
        <nombre_via>St Mario</nombre_via>
        <codigo_postal>467849</codigo_postal>
        <pais>USA</pais>
    </direccion>
</compania> 
</videojuego>