=== YinaryHdz/WSActividadesLMSGI/Actividad12/_DTD_Videojuego_02.dtd
<!ELEMENT videojuego (info_basica,programadores,compania)>

    <!ELEMENT info_basica (titulo,fecha_creacion,nota_personal)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT fecha_creacion (#PCDATA)>
    <!ELEMENT nota_personal (#PCDATA)>

    <!ELEMENT programadores (programador+)>

    <!ELEMENT programador (nombre,apellidos,dni,fecha_nacimiento,direccion)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT dni (#PCDATA)>
    <!ELEMENT fecha_nacimiento (#PCDATA)>
    <!ELEMENT direccion (tipo_via,nombre_via,codigo_postal,pais)>
        <!ELEMENT tipo_via (#PCDATA)>
        <!ELEMENT nombre_via (#PCDATA)>
        <!ELEMENT codigo_postal (#PCDATA)>
        <!ELEMENT pais (#PCDATA)>
    
    <!ELEMENT compania (nombre,nif, direccion)>
    <!ELEMENT nif (#PCDATA)>

    <!ATTLIST videojuego id ID #REQUIRED>
    <!ATTLIST programador id CDATA #REQUIRED>
    <!ATTLIST compania identificacion CDATA #REQUIRED>

=== YinaryHdz/WSActividadesLMSGI/Actividad12/_DTD_Videojuego_02.xml
<?xml version="1.0" encoding="UTF-8" standalone ="no"?>
<!DOCTYPE videojuego SYSTEM "_DTD_Videojuego_02.dtd">
<videojuego id="Dut674" >
    <info_basica>
        <titulo>GTA</titulo>
        <fecha_creacion>20/06/1991</fecha_creacion>
        <nota_personal> 10 </nota_personal> 
    </info_basica>
    <programadores>
        <programador id = "10">
            <nombre>Tommara</nombre>
            <apellidos>Evans Peters </apellidos>
            <dni>1289334TGR</dni>
            <fecha_nacimiento> 02/07/1975</fecha_nacimiento>
            <direccion>
                <tipo_via>Calle</tipo_via>
                <nombre_via>St vodka</nombre_via>
                <codigo_postal>93456</codigo_postal>
                <pais>Australia</pais>
            </direccion>
        </programador> 
        <programador id = "20">
            <nombre>Taylor</nombre>
            <apellidos>Swift</apellidos>
            <dni>98765432D</dni>
            <fecha_nacimiento>30/09/1986</fecha_nacimiento>
            <direccion>
                <tipo_via>Calle</tipo_via>
                <nombre_via>St Snake</nombre_via>
                <codigo_postal>45678</codigo_postal>
                <pais>USA</pais>
            </direccion>
        </programador> 
    </programadores>
    <compania identificacion="jyuryt67">
        <nombre>DMA Designs</nombre>
        <nif>98761234F</nif>
        <direccion>
            <tipo_via>Calle</tipo_via>
            <nombre_via>St vice</nombre_via>
            <codigo_postal>467849</codigo_postal>
            <pais>inglaterra</pais>
        </direccion>
    </compania> 
    </videojuego>
