=== YinaryHdz/WSActividadesLMSGI/Actividad15/_02_Ciudad.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="ciudad">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[A-Z]{1}[a-z]{3,20}"></xs:pattern>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element> 
                <xs:element name="poblacion">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="100"/>
                            <xs:maxInclusive value="100000"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element> 
                <xs:element name="alcalde">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z]{1}[a-z]{1,9}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="apellido">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z]{1}[a-z]*\s[A-Z]{1}[a-z]*"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="telefono">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\+34\d{9}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="correoElectronico">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="edad" use="required">
                            <xs:simpleType>
                            <xs:restriction base="xs:integer">
                                <xs:minInclusive value="18"/>
                                <xs:maxInclusive value="120"/>
                            </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element> 
                <xs:element name="funcionarios">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="funcionario" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombreCompleto">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:maxLength value="50"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="codigoPostal">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:pattern value="\d{5}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element> 
                                        <xs:element name="fechaNacimiento">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="\d{2}\/\d{2}\/\d{4}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element> 
                                        <xs:element name="contraseÃ±a">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[A-Z](\d{2})+[%$@!]"></xs:pattern>
                                                    <xs:minLength value="10"></xs:minLength>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element> 
                                        <xs:element name="numeroCuenta">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="ES\d{4}\s\d{4}\s\d{4}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" use="required">
                                        <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:pattern value="[\da-zA-Z]{1,10}"/>
                                        </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence> 
                    </xs:complexType>
                </xs:element>
            </xs:sequence> 
            <xs:attribute name="codigoIdentificador" use="required">
                <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="\D\D-[\d]{2,5}"/>
                </xs:restriction>
                </xs:simpleType>
            </xs:attribute> 
        </xs:complexType>
    </xs:element>

</xs:schema>

=== YinaryHdz/WSActividadesLMSGI/Actividad15/_01_Ciudad.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ciudad xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="_02_Ciudad.xsd"
codigoIdentificador="rt-4534">
<nombre>Madrid</nombre>
<poblacion>90009</poblacion>
<alcalde edad="25">
    <nombre>Carlos</nombre>
    <apellido>Gomez Perez</apellido>
    <telefono>+34987654321</telefono>
    <correoElectronico>+gomez%perez@alcalde.com</correoElectronico>
</alcalde>
<funcionarios>
    <funcionario id="8909edsfF">
        <nombreCompleto>Jose Lopez Rodriguez</nombreCompleto>
        <codigoPostal>28030</codigoPostal>
        <fechaNacimiento>23/12/1990</fechaNacimiento>
        <contraseña>A2567830910%</contraseña>
        <numeroCuenta>ES2345 4356 3245</numeroCuenta>
    </funcionario>
</funcionarios>
</ciudad>
